name: travel_tips
description: A tour booking app.
publish_to: 'none' 
version: 1.0.2+2

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2  
  json_annotation: ^4.8.0
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter_icons:
  android: true
  image_path: "assets/app_logo.png"
  

flutter_native_splash:
  background_image: "assets/background.png"
  background_image_dark: "assets/background.png"

  android_12:
    image: assets/splash_screen.png
    icon_background_color: "
    image_dark: assets/splash_screen_invert.png
    icon_background_color_dark: "

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

fonts:
   - family: OpenSans
     fonts:
       - asset: assets/fonts/OpenSans-Regular.ttf
       - asset: assets/fonts/OpenSans-Medium.ttf
  
  
  
  
  
  

